if 0 | endif

set nocompatible
filetype off
filetype plugin indent off

" Load NeoBundle
if has('vim_starting')
  set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))
  NeoBundleFetch 'Shougo/neobundle.vim'

  NeoBundle 'tomasr/molokai'

  NeoBundleCheck
call neobundle#end()

" encoding settings
set encoding=utf-8
scriptencoding utf-8
set fileencodings=utf-8,cp932,latin1
if has('win32unix') || has('win32') || has('win64')
  set termencoding=utf-8
  set fileformat=dos
  set fileformats=dos,unix,mac
else
  set termencoding=utf-8
  set fileformat=unix
  set fileformats=unix,dos,mac
endif

" edit settings
set tabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set ambiwidth=double
set hlsearch
set showmatch
set paste

" vi settings
syntax on
colorscheme molokai
set shellslash
set statusline=[%L]\ %t\ %y%{'['.(&fenc!=''?&fenc:&enc).':'.&ff.']'}%r%m%=%c:%l/%L
set laststatus=2

" load plugin
filetype plugin indent on
" disable auto comment to next line
autocmd FileType * setlocal formatoptions-=ro
" disable auto indent
autocmd FileType * setlocal noautoindent
autocmd FileType * setlocal nosmartindent
autocmd FileType * setlocal nocindent

